POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "That's video 03",
    "duration": 270
}

###
GET http://localhost:3333/videos


###
PUT http://localhost:3333/videos/44e8ebf2-0b01-4f3e-83d1-6cebd0793216
Content-type: application/json

{
    "title": "Video 07",
    "description": "That's video 07",
    "duration": 360
}

###
DELETE http://localhost:3333/videos/fcbf9dcd-8164-44fe-a59d-76d76644b8c6
